version: '2'

services:
     spring-cloud-eureka: 
# 默认环境变量
#      environment:
#        - SERVER_VERSION=1.0.2-SNAPSHOT
#        - SERVER_BIN=/usr/local/bin/wesign-mss-open-app.jar
# 自定义hosts和服务器可运行的war/jar文件挂载
#       volumes: 
#         - "/etc/hosts:/etc/hosts"
# windows 10下挂载文件和目录到宿主机
#         - "/c/Users/Mloong/.m2/repository/cn/luliangwei/docker-demo/0.0.1-SNAPSHOT/docker-demo-0.0.1-SNAPSHOT.jar:/usr/local/bin/docker-demo-0.0.1-SNAPSHOT.jar"
#         - "/d/docker/docker-demo-0.0.1-SNAPSHOT.jar:/usr/local/bin/docker-demo-0.0.1-SNAPSHOT.jar"
       image: "registry.cn-hangzhou.aliyuncs.com/luliangwei/demo:spring-cloud-eureka-1.0.0-SNAPSHOT"
       build: .
       ports: 
         - "5683:5683"
         - "45683:45683"
       restart: always
       stdin_open: true
