spring:
  application:
    name: spring-admin-client

#  boot:
#    admin:
#      url:
#      - http://localhost:1026
##      api-path: instances
#      routes:
#        endpoints:
#        - env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      
server:
  port: 10200
  
eureka:
  instance:
    hostname: localhost
    appname: spring-admin-client
    lease-renewal-interval-in-seconds: 10
# 1.5.16版本不需要这个,2.0版本需要
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.init}
# 1.5.16版本不需要这个,2.0版本需要
      management.context-path: /actuator
  client:
    service-url:
      defaultZone: http://localhost:4683/eureka/
management:
  security:
    enabled: false
# 1.5.16版本不需要这个,2.0版本需要
  context-path: /actuator
  
info:
  version: '@project.version@'